name: 3-D Contrib Graph
on:
  schedule: [{cron: "0 0 * * 0"}]     # weekly, Sunday 00:00 UTC
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: yoshi389111/github-profile-3d-contrib@v0.9.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          author_name: ArnoldW-dev
          output_path: ./profile-3d-contrib.svg
